# Root project information
   sonar.host.url=http://13.229.238.92:9000/
   sonar.projectKey=Sonar:umamaheswaran
   sonar.projectName=sonarjs
   sonar.projectVersion=1.0-SNAPSHOT
   # Some properties that will be inherited by the modules   
   sonar.sources=/root/helios/sonarjs/src
   # Redefine properties
   # Comma-separated paths to test source directories (optional)
   sonar.tests=/root/helios/sonarjs/test
   sonar.language=java